### ISSUE TITLE
Run `build` before `new`

### ISSUE THREAD

**Issue by JohnTitor** [student-kyushu/hibana#16]
### Subject

`new`する前に`build`したときはどうするのが一番良いか

### Opinion

今は`new`の前に`build`をすると虚無が生成されます
先に`new`してね～というのか暗黙的によしなにやるのがいいのか，とりあえず今の振る舞いから変えたいです
開発しておきながら他の静的サイトジェネレータをよく知らないので困っています
意見大募集

**Comment by k-nasa** [comment]
虚無が生成されるって、何もされないってこと？
ディレクトリだけ生成されちゃうのかと思った。

**Comment by k-nasa** [comment]
あ。ごめんされてた、publicだけできちゃうのか、、、

暗黙には作らずに、メッセージを出すのが良いかと思います。

**Comment by JohnTitor** [comment]
めっっちゃ婉曲な表現で分かりづらかったですね，申し訳ないです……
メッセージ出すなら，先に`new`やってねと言ってエラーにする，みたいなので大丈夫でしょうか

**Comment by k-nasa** [comment]
だね。追加します！
