### ISSUE TITLE
Reviews for PRs

### ISSUE THREAD

**Issue by diplozoon** [student-kyushu/hibana#3]
今のところ，PRをマージするにはレビューが必要です．
意図としては，

- レビューを必須とすることで，他人のコードを読むことになる
- チーム開発っぽいことができる
- より公平性を持てる

みたいなのがあります．

しかし，レビュー必須のせいでマージまで時間がかかるのも事実です．
必要かどうか，諸氏の意見をうかがいたいです．

**Comment by east9698** [comment]
今の所、開発に参加しているメンバーはそう多くないので、PRを発行した際は積極的にメンションするなどアピールして周囲に促していくというのが良さそう。

現段階でのレビュー必須は賛成です〜

**Comment by k-nasa** [comment]
@diplozoon @east9698 レビュー必須で良いかと思います。
collaboratorとして招待して欲しいかな

**Comment by diplozoon** [comment]
おkです！！！(招待芸、お風呂から出たらやるます！！)

**Comment by diplozoon** [comment]
アクティブメンバーからの承認を得たので，レビューは残す方向でいきます！！！！！
