### ISSUE TITLE
Clean up labels 

### ISSUE THREAD

**Issue by diplozoon** [student-kyushu/hibana#5]
### Subject

Labelsを良い感じにしたい

### Opinion

俺だ．
ラベルについてだが，今後も開発が続くのであればイケてる感じに整理した方がフィルタもしやすいし便利になると思う．
諸氏が日本語の方が好みならそのようにしても良いし，とにかく使いやすいようにしたい．
ラボメンの意見を聞かせてくれ．
エル・プサイ・コングルゥ．

cc: @k-nasa @east9698

**Comment by k-nasa** [comment]
@diplozoon どうだろ。とりあえず既存のでいい気がしている

**Comment by diplozoon** [comment]
@k-nasa まじすか～，まあそんなにissueあがりそうにないしそのままでもいいかもですね～

**Comment by diplozoon** [comment]
僕の渾身のボケが刺さらなくて泣いています

まあ確かにデフォルトと若干の追加で回しても良いですねとなりましたのでそうしましょう
