### ISSUE TITLE
Road to v0.1.0

### ISSUE THREAD

**Issue by diplozoon** [student-kyushu/hibana#8]
### Subject

ひとまずの目標を決めたい

### Opinion

今は何も指針などがないので，開発しろって言われても何をすればいいのかわからんこみたいな状態です
なのでひとまず静的サイトジェネレータと呼べるレベルまで持っていくために目標というかこれとこれとこれをまず出来るようにしたいねというのを決めたいです
一応静的サイトジェネレータと呼べるようになったときのバージョンをv0.1.0としてマイルストーンも置いています(バージョンの命名については今は僕の好みなので推しのバージョン命名規則があれば気軽に議論しましょう)

**Comment by diplozoon** [comment]
Markdown to htmlなら[pulldown-cmark](https://github.com/raphlinus/pulldown-cmark)とか良さそうだな～と思いました

**Comment by k-nasa** [comment]
@diplozoon @east9698  Projectに必要そうなのを書いていくのが良さそう?

**Comment by diplozoon** [comment]
@k-nasa なるほど～
一応つくってみたのですが見てもらえませんか？

**Comment by diplozoon** [comment]
なんかProjectsさん結構良さげなのでそこで回すぞ！！
